Feature/21 press api
avshashov/molecule-backend pull request #10
Opened 2023-11-26 08:28 UTC by avshashov

[Task #21](https://tree.taiga.io/project/avshashov-molecule-project/us/21?kanban-status=5967620)

2023-11-26 17:51 UTC, Nickellick requested changes
есть правки

2023-11-26 17:51 UTC, Nickellick commented on app/schemas/__init__.py
Лучше использовать абсолютные имена

2023-11-26 17:51 UTC, Nickellick commented on pyproject.toml
Для совместимости версии нужно жёстко закрепить - не выше 0.0.6 а именно 0.0.6. Тоже самое с aiofiles

2023-11-27 03:02 UTC, avshashov commented on app/schemas/__init__.py
Исправлено

2023-11-27 03:02 UTC, avshashov commented on pyproject.toml
Исправлено

2023-11-27 13:00 UTC, Nickellick approved these changes

2023-11-27 13:00 UTC, merged